version: '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - $MYSQL_TCP_PORT:3306
    environment: &environment
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  php:
    image: ngyuki/php-dev:7.2
    volumes:
      - ./:/app/
    working_dir: /app/
    environment:
      <<: *environment
    command:
      - sh
      - -c
      - |
        composer install -o --ansi --prefer-dist

        echo 'wait for mysql...'
        while ! mysqladmin ping -h "$$MYSQL_HOST" 2>&1; do
          sleep 1
        done

        mysql -v <<SQL
          create create database "$${MYSQL_DATABASE}_old"
          create create database "$${MYSQL_DATABASE}_new"
          grant all on \`$${MYSQL_DATABASE}\\_%\`.* to "$$MYSQL_USER"@"%";
        SQL

        php -v
        echo
        exec tail -f /dev/null
